# Generated by Django 2.1 on 2018-08-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('no_handphone', models.CharField(max_length=15)),
                ('bidang', models.CharField(choices=[('MAT', 'Matematika SMA'), ('FIS', 'Fisika SMA'), ('KIM', 'Kimia SMA'), ('BIO', 'Biologi SMA'), ('KOM', 'Komputer SMA'), ('AST', 'Astronomi SMA'), ('GEO', 'Geografi SMA'), ('EKO', 'Ekonomi SMA'), ('KEB', 'Kebumian SMA'), ('MAP', 'Matematika SMP'), ('BIP', 'Biologi SMP'), ('FIP', 'Fisika SMP'), ('IPS', 'IPS SMP')], help_text='Bidang hanya dapat diatur sekali di awal.', max_length=3)),
                ('role', models.CharField(choices=[('SIS', 'Siswa'), ('GUR', 'Guru')], default='SIS', help_text='Role hanya dapat diatur sekali di awal. Nilai guru tidak disertakan dalam ranking.', max_length=3)),
                ('asal_sekolah', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('guru_pembimbing', models.CharField(blank=True, default='', help_text='Opsional', max_length=100)),
                ('no_handphone_guru', models.CharField(blank=True, default='', help_text='Opsional', max_length=15)),
            ],
        ),
    ]
