# Generated by Django 2.1 on 2018-08-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=100)),
                ('jadwal', models.CharField(default='-', max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('link_panduan', models.URLField(blank=True, null=True)),
                ('waktu_buka', models.DateTimeField(blank=True, null=True)),
                ('waktu_mulai', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NomorPaket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=100)),
                ('open_time', models.DateTimeField(verbose_name='Open Time')),
                ('close_time', models.DateTimeField(verbose_name='Close Time')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(default='-')),
            ],
        ),
    ]
