# Generated by Django 2.1 on 2018-08-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('soal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paket',
            name='bundel_soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soal.BundelSoal'),
        ),
        migrations.AddField(
            model_name='paket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Event'),
        ),
        migrations.AddField(
            model_name='paket',
            name='nomor_paket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.NomorPaket'),
        ),
        migrations.AddField(
            model_name='nomorpaket',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program'),
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program'),
        ),
    ]
